### ISSUE TITLE
ink@next: TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by sdgluck** [vadimdemedes/ink#115]
I am receiving this error after updating my app to use `ink@next`, and moving from `ink-redux` to `redux` with `react-redux`:

```sh
  TypeError: Cannot read property 'length' of undefined
      at buildLayout (C:\_dev\htdocs\wpk-cli\wpk\packages\command-build\node_modules\ink\build\create-renderer.js:92:23)
      at buildLayout (C:\_dev\htdocs\wpk-cli\wpk\packages\command-build\node_modules\ink\build\create-renderer.js:100:11)
      at buildLayout (C:\_dev\htdocs\wpk-cli\wpk\packages\command-build\node_modules\ink\build\create-renderer.js:51:31)
      at node (C:\_dev\htdocs\wpk-cli\wpk\packages\command-build\node_modules\ink\build\create-renderer.js:221:9)
      at onRender (C:\_dev\htdocs\wpk-cli\wpk\packages\command-build\node_modules\ink\build\render.js:65:9)
      at invokeFunc (C:\_dev\htdocs\wpk-cli\wpk\packages\command-build\node_modules\lodash.throttle\index.js:160:19)
      at trailingEdge (C:\_dev\htdocs\wpk-cli\wpk\packages\command-build\node_modules\lodash.throttle\index.js:207:14)
      at Timeout.timerExpired [as _onTimeout] (C:\_dev\htdocs\wpk-cli\wpk\packages\command-build\node_modules\lodash.throttle\index.js:195:14)
      at ontimeout (timers.js:498:11)
      at tryOnTimeout (timers.js:323:5)
      at Timer.listOnTimeout (timers.js:290:5)
```

Not sure what other information to provide, so please let me know if there is anything.

Code for the refactor of `ink` -> `ink@next` is here in case that is useful: https://github.com/wpk-cli/wpk/blob/ink-next/packages/command-build/src/terminal/index.js

**Comment by sdgluck** [comment]
Looks like there is an assumption that the property `node.childNodes` always exists, but in this instance it doesn't. Seems like a bug. I can put in a PR with a fix if you agree.

**Comment by zkat** [comment]
@vadimdemedes I can confirm I'm getting this error, too.

Repro steps:

1. `git clone https://github.com/npm/libpickupdates && cd libpickupdates`
2. `npm i && npm run build`
3. `node index.js` and continue without selecting any packages to update
4. crash is reproduced, every time

**Comment by vadimdemedes** [comment]
With the latest `2.0.0-13` release, this issue shouldn't be occurring anymore, thanks for the report!
