### ISSUE TITLE
ink@next: TypeError: insertInContainerBefore is not a function

### ISSUE THREAD

**Issue by sdgluck** [vadimdemedes/ink#116]
(After fixing #115 locally.)

Get this error at some point during my app rendering:

```sh
  TypeError: insertInContainerBefore is not a function
      at commitPlacement (C:\_dev\htdocs\wpk-cli\wpk\packages\command-build\node_modules\react-reconciler\cjs\react-reconciler.development.js:8605:11)
      at commitAllHostEffects (C:\_dev\htdocs\wpk-cli\wpk\packages\command-build\node_modules\react-reconciler\cjs\react-reconciler.development.js:9393:11)
      at Object.invokeGuardedCallbackImpl (C:\_dev\htdocs\wpk-cli\wpk\packages\command-build\node_modules\react-reconciler\cjs\react-reconciler.development.js:2111:10)
      at invokeGuardedCallback (C:\_dev\htdocs\wpk-cli\wpk\packages\command-build\node_modules\react-reconciler\cjs\react-reconciler.development.js:2289:31)
      at commitRoot (C:\_dev\htdocs\wpk-cli\wpk\packages\command-build\node_modules\react-reconciler\cjs\react-reconciler.development.js:9632:7)
      at completeRoot (C:\_dev\htdocs\wpk-cli\wpk\packages\command-build\node_modules\react-reconciler\cjs\react-reconciler.development.js:11135:3)
      at performWorkOnRoot (C:\_dev\htdocs\wpk-cli\wpk\packages\command-build\node_modules\react-reconciler\cjs\react-reconciler.development.js:11064:9)
      at performWork (C:\_dev\htdocs\wpk-cli\wpk\packages\command-build\node_modules\react-reconciler\cjs\react-reconciler.development.js:10972:7)
      at performSyncWork (C:\_dev\htdocs\wpk-cli\wpk\packages\command-build\node_modules\react-reconciler\cjs\react-reconciler.development.js:10946:3)
      at requestWork (C:\_dev\htdocs\wpk-cli\wpk\packages\command-build\node_modules\react-reconciler\cjs\react-reconciler.development.js:10815:5)
      at scheduleWork (C:\_dev\htdocs\wpk-cli\wpk\packages\command-build\node_modules\react-reconciler\cjs\react-reconciler.development.js:10610:5)
      at Object.enqueueSetState (C:\_dev\htdocs\wpk-cli\wpk\packages\command-build\node_modules\react-reconciler\cjs\react-reconciler.development.js:4522:5)
      at Provider.Component.setState (C:\_dev\htdocs\wpk-cli\wpk\packages\command-build\node_modules\react\cjs\react.development.js:375:16)
      at C:\_dev\htdocs\wpk-cli\wpk\packages\command-build\node_modules\react-redux\lib\components\Provider.js:65:14
      at Object.dispatch (C:\_dev\htdocs\wpk-cli\wpk\packages\command-build\node_modules\redux\lib\redux.js:220:7)
      at Terminal.onBuilderStatus (C:\_dev\htdocs\wpk-cli\wpk\packages\command-build\dist\terminal\components\Terminal.js:125:16)
```

Looks like ink's reconciler doesn't implement this method?

**Comment by vadimdemedes** [comment]
I pushed a fix for it yesterday, but didn't publish, until now. If you update to latest `ink@next`, it should be fixed.
