### ISSUE TITLE
Cannot read property 'normalize' of undefined

### ISSUE THREAD

**Issue by jdeniau** [vadimdemedes/ink#179]
Apparently there is a bug while using `height` and `textWrap`: 

```js
import React from 'react';
import { render, Box } from 'ink';

const text =
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris accumsan pellentesque enim, et scelerisque lacus varius et. Vivamus finibus nisi vel lorem vestibulum mollis in sed purus. Ut vitae quam felis. Integer cursus, quam at lacinia iaculis, mauris lacus tempus augue, at lobortis nibh libero in lectus. Suspendisse congue facilisis velit, at cursus ante tincidunt a. Duis sagittis faucibus ligula, ut euismod nulla maximus sit amet. Suspendisse pellentesque facilisis erat vel pretium. Donec tempor, elit tempus tempor mattis, nunc urna ultrices felis, id viverra leo justo ac arcu. Ut ac erat id lectus consequat faucibus eu elementum lorem. Aliquam ut justo ac justo tempor convallis at vitae neque. Nam a purus maximus, rhoncus dolor vel, bibendum nunc. Donec et malesuada turpis. Vestibulum lacinia lectus eu sem cursus laoreet.';

function SomeText() {
  return <Box textWrap="wrap">{text}</Box>;
}

function App() {
  return (
    <Box height={3}>
      <SomeText />
    </Box>
  );
}

render(<App />);
```

This error is found : 
```
TypeError: Cannot read property 'normalize' of undefined
    at module.exports (/home/jdeniau/code/changelog-view/node_modules/slice-ansi/index.js:43:29)
    at Output.write (/home/jdeniau/code/changelog-view/node_modules/ink/build/output.js:51:57)
    at renderNodeToOutput (/home/jdeniau/code/changelog-view/node_modules/ink/build/render-node-to-output.js:107:12)
    at renderNodeToOutput (/home/jdeniau/code/changelog-view/node_modules/ink/build/render-node-to-output.js:146:7)
    at renderNodeToOutput (/home/jdeniau/code/changelog-view/node_modules/ink/build/render-node-to-output.js:146:7)
    at renderNodeToOutput (/home/jdeniau/code/changelog-view/node_modules/ink/build/render-node-to-output.js:146:7)
    at Instance.node [as renderer] (/home/jdeniau/code/changelog-view/node_modules/ink/build/renderer.js:148:37)
    at Instance.onRender (/home/jdeniau/code/changelog-view/node_modules/ink/build/instance.js:70:14)
    at resetAfterCommit (/home/jdeniau/code/changelog-view/node_modules/ink/build/reconciler.js:24:14)
    at commitRoot (/home/jdeniau/code/changelog-view/node_modules/react-reconciler/cjs/react-reconciler.development.js:10734:3)
```

**Comment by isaacs** [comment]
Another app that causes the same error, maybe a clue:

```jsx
const React = require('react')
const {Box, render} = require('ink')

const App = () => (
  <Box flexDirection="column">
    <Box>{'this is fine'}</Box>
    {''}
  </Box>
)

render(<App />)
```

```
$ node -e 'require("import-jsx")("./break-box.js")'
/Users/isaacs/dev/js/treport/node_modules/slice-ansi/index.js:43
	const arr = Array.from(str.normalize());
	                           ^

TypeError: Cannot read property 'normalize' of undefined
    at module.exports (/Users/isaacs/dev/js/treport/node_modules/slice-ansi/index.js:43:29)
    at Output.write (/Users/isaacs/dev/js/treport/node_modules/ink/build/output.js:51:57)
    at renderNodeToOutput (/Users/isaacs/dev/js/treport/node_modules/ink/build/render-node-to-output.js:115:12)
    at renderNodeToOutput (/Users/isaacs/dev/js/treport/node_modules/ink/build/render-node-to-output.js:146:7)
    at renderNodeToOutput (/Users/isaacs/dev/js/treport/node_modules/ink/build/render-node-to-output.js:146:7)
    at Instance.node [as renderer] (/Users/isaacs/dev/js/treport/node_modules/ink/build/renderer.js:148:37)
    at Instance.onRender (/Users/isaacs/dev/js/treport/node_modules/ink/build/instance.js:70:14)
    at resetAfterCommit (/Users/isaacs/dev/js/treport/node_modules/ink/build/reconciler.js:24:14)
    at commitRoot (/Users/isaacs/dev/js/treport/node_modules/react-reconciler/cjs/react-reconciler.development.js:10913:3)
    at /Users/isaacs/dev/js/treport/node_modules/react-reconciler/cjs/react-reconciler.development.js:12401:5
```

**Comment by isaacs** [comment]
This is a very mysterious bug.  I could've sworn everything was working as recently as last night, but today, I'm getting this error all over the place.  I've tried rolling back the versions of Ink, of React, you name it, but I can't seem to track down what changed to make this stop working.

**Comment by isaacs** [comment]
Here's the first bad commit:

```
$ git bisect bad
1a9ba27397c92a4301c0c80e451a39be4aa7a650 is the first bad commit
commit 1a9ba27397c92a4301c0c80e451a39be4aa7a650
Author: Vadim Demedes <vdemedes@gmail.com>
Date:   Wed Mar 27 21:39:30 2019 -0700

    Rewrite text squashing and text wrapping

:040000 040000 6e146df209ba3589428b759b106d1ca4cb6c2ace 6b54bc0c823cc482fd267d428f3b860487949711 M      src
:040000 040000 a26488afb4aa8f7d89f7e2b798b734269241964e 637ab79eaa240cb703463ca407cf50722317cfd1 M      test
```

**Comment by vadimdemedes** [comment]
Looking into it!

**Comment by vadimdemedes** [comment]
Fix turned out to be pretty simple - https://github.com/vadimdemedes/ink/commit/8f44d6ded167578df7b963d066171ebf208669b9. Could you test Ink's master branch in your apps before I create a new release?

**Comment by isaacs** [comment]
That appears to fix the problem without affecting any of my snapshots, so
we're probably good! :)

**Comment by vadimdemedes** [comment]
I thought I deleted my comment fast enough, haha, sorry.

So https://github.com/vadimdemedes/ink/commit/8f44d6ded167578df7b963d066171ebf208669b9 fixed your problem, @isaacs, which is different from what was reported originally by @jdeniau.

@jdeniau Reason you're encountering this issue, is that text is taller than 3 rows (`height={3}`). I think the correct solution here would be to cut off extra lines to ensure that box is 3 rows tall no matter what. Working on a fix.

**Comment by isaacs** [comment]
This seems to fix the height issue?  Not sure what other side effects it might have.

```patch
diff --git a/src/output.js b/src/output.js
index 6d32b64..4f92147 100644
--- a/src/output.js
+++ b/src/output.js
@@ -34,6 +34,10 @@ export default class Output {
 			const length = stringLength(line);
 			const currentLine = this.output[y + offsetY];
 
+			if (currentLine === undefined) {
+				continue;
+			}
+
 			for (const transformer of transformers) {
 				line = transformer(line);
 			}
```

**Comment by vadimdemedes** [comment]
This fix is better than the one I was working on, thanks!

**Comment by vadimdemedes** [comment]
Fix is out in https://github.com/vadimdemedes/ink/releases/tag/v2.1.1. Let me know if there are any issues and I'll reopen it ;)

**Comment by CraftingGamerTom** [comment]
This is still, or once again an issue. Let me know if I should open a new ticket instead of reopening this one.

**Description**
`nuxt-link` components that are missing a `to="some-value"` argument results in an unclear error and significantly slows down loading of the page affected.

Here is an example

**test.vue**
```
<template>
  <nuxt-link>
    xxxxxx
  </nuxt-link>
</template>
```
When the page is rendered we recieve this error
![image](https://user-images.githubusercontent.com/10101712/80320827-bf4ddb80-87e6-11ea-8018-ede209b73171.png)
**Text:** 
> Cannot read property '_normalized' of undefined
> An error occurred while rendering the page. Check developer tools console for details.


Example of proper implementation that will silence the error - requires hard refresh after fixing to see change
```
<template>
  <nuxt-link to="#">
    xxxxxx
  </nuxt-link>
</template>
```

**Comment by PLQin** [comment]
删除掉 `layouts\default.vue` 中的 `script` 试试 

<small>Try deleting the 'script' in 'layouts\default.vue'</small>
