### ISSUE TITLE
backgroundColor prop in Text component fails

### ISSUE THREAD

**Issue by smtrd3** [vadimdemedes/ink#410]
I am using the typescript template of create-ink-app,
backgroundColor in &lt;Text/&gt; component throws this error: 

TypeError: chalk_1.default[method] is not a function
    at Object.exports.default (/home/smtrd3/projects/devenv/node_modules/ink/build/colorize.js:21:39)
    at transform (/home/smtrd3/projects/devenv/node_modules/ink/build/components/Text.js:24:42)
    at Output.get (/home/smtrd3/projects/devenv/node_modules/ink/build/output.js:40:28)
    at Object.exports.default (/home/smtrd3/projects/devenv/node_modules/ink/build/renderer.js:29:74)
    at Object.Ink.onRender [as onImmediateRender] (/home/smtrd3/projects/devenv/node_modules/ink/build/ink.js:49:78)
    at invokeFunc (/home/smtrd3/projects/devenv/node_modules/lodash/lodash.js:10359:23)
    at leadingEdge (/home/smtrd3/projects/devenv/node_modules/lodash/lodash.js:10369:26)
    at Object.debounced [as onRender] (/home/smtrd3/projects/devenv/node_modules/lodash/lodash.js:10436:20)
    at resetAfterCommit (/home/smtrd3/projects/devenv/node_modules/ink/build/reconciler.js:42:22)
    at commitRootImpl (/home/smtrd3/projects/devenv/node_modules/react-reconciler/cjs/react-reconciler.development.js:15066:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! devenv@0.0.0 start: `npm run build && dist/cli.js`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the devenv@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/smtrd3/.npm/_logs/2020-12-31T06_36_59_044Z-debug.log

**Comment by vadimdemedes** [comment]
Could you show your app code?
