### ISSUE TITLE
Using backgroundColor breaks ink

### ISSUE THREAD

**Issue by Twiggeh** [vadimdemedes/ink#428]
I get the error 
```
/mnt/Storage/projects/Webdev/CodeGeneration/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

TypeError: chalk_1.default[method] is not a function
```
 with writing

```jsx
<Text backgroundColor='bgBlackBright'> 
```
Any of the suggested strings breaks with the same error, not jut `bgBlackBright`

<details>
<summary>Dependencies & Versions</summary>

```json
"@types/node": "^14.14.35",
"@types/react": "^17.0.3",
"ink": "^3.0.8",
"react": "^17.0.2",
"typescript": "^4.2.3"
```
</details>

<details>
<summary> Stack Trace </summary>

```
TypeError: chalk_1.default[method] is not a function
    at Object.exports.default (/mnt/Storage/projects/Webdev/CodeGeneration/node_modules/ink/build/colorize.js:21:39)
    at transform (/mnt/Storage/projects/Webdev/CodeGeneration/node_modules/ink/build/components/Text.js:24:42)
    at Output.get (/mnt/Storage/projects/Webdev/CodeGeneration/node_modules/ink/build/output.js:40:28)
    at Object.exports.default (/mnt/Storage/projects/Webdev/CodeGeneration/node_modules/ink/build/renderer.js:29:74)
    at Object.Ink.onRender [as onImmediateRender] (/mnt/Storage/projects/Webdev/CodeGeneration/node_modules/ink/build/ink.js:49:78)
    at invokeFunc (/mnt/Storage/projects/Webdev/CodeGeneration/node_modules/lodash/lodash.js:10401:23)
    at leadingEdge (/mnt/Storage/projects/Webdev/CodeGeneration/node_modules/lodash/lodash.js:10411:26)
    at Object.debounced [as onRender] (/mnt/Storage/projects/Webdev/CodeGeneration/node_modules/lodash/lodash.js:10478:20)
    at resetAfterCommit (/mnt/Storage/projects/Webdev/CodeGeneration/node_modules/ink/build/reconciler.js:42:22)
    at commitRootImpl (/mnt/Storage/projects/Webdev/CodeGeneration/node_modules/react-reconciler/cjs/react-reconciler.development.js:15066:5)
    ```
</details>

**Comment by sindresorhus** [comment]
This is really just the docs being slightly vague. You should not prefix the color with `bg`. That's handled for you.

https://github.com/vadimdemedes/ink#color

**Comment by Twiggeh** [comment]
I see, it's just the autocomplete showed it prefixed with "bg" - its passing the type from chalk to the `<Text>` component:
https://github.com/vadimdemedes/ink/blob/259edd47968081b23b176b7a7cfecc5e5757845d/src/components/Text.tsx#L2

![image](https://user-images.githubusercontent.com/23149166/114594138-334df180-9c8d-11eb-8150-aef2cb6a6f96.png)


I am not sure whether there are other components exposing the chalk list, I could add the list to the `<Text>` if that's the only place its needed :)
