### ISSUE TITLE
Can't run the first example

### ISSUE THREAD

**Issue by lodenrogue** [vadimdemedes/ink#429]
I'm new to ink and I can't get the example to run. Here's what I'm doing:

```sh
npm init
npm install ink react
```

I then create a file called app.js with the following contents

```
import React, {useState, useEffect} from 'react';
import {render, Text} from 'ink';

const Counter = () => {
	const [counter, setCounter] = useState(0);

	useEffect(() => {
		const timer = setInterval(() => {
			setCounter(previousCounter => previousCounter + 1);
		}, 100);

		return () => {
			clearInterval(timer);
		};
	}, []);

	return <Text color="green">{counter} tests passed</Text>;
};

render(<Counter />);
```

Then I run
```sh
node app.js
```

And I get the following error:
```
import React, {useState, useEffect} from 'react';
       ^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**Comment by sindresorhus** [comment]
Seems like you missed the "getting started" section which explains the manual required setup.

**Comment by lodenrogue** [comment]
It doesn't explain anything. Just says to use Yoga. How do I set it up for this project? Their github instructions seem unrelated.

**Comment by lodenrogue** [comment]
You should update Ink's documentation and explain how to install Yoga

**Comment by sindresorhus** [comment]
That's not what I'm referring to. You need to set up Babel.

**Comment by lodenrogue** [comment]
Do me a favor. Go on the Readme page and press ctrl-f or cmd-f and search for the word babel. It doesn't appear anywhere.

**Comment by lodenrogue** [comment]
I see it now thank you.

**Comment by lodenrogue** [comment]
It's hidden under the manual set up arrow
