### ISSUE TITLE
Problems with babel-preset-env

### ISSUE THREAD

**Issue by pe3** [vadimdemedes/ink#43]
This example:
```
const {h, render, Component, Text} = require('ink')

class Counter extends Component {
    constructor() {
        super();

        this.state = {
            i: 0
        };
    }

    render() {
        return (
            <Text green>
                {this.state.i} iterations passed
            </Text>
        );
    }

    componentDidMount() {
        this.timer = setInterval(() => {
            this.setState({
                i: this.state.i + 1
            });
        }, 100);
    }

    componentWillUnmount() {
        clearInterval(this.timer);
    }
}

const Demo = () => <div>Petri</div>
//const App = Demo
const App = Counter

const unmount = render(<App/>)

setTimeout(() => {
    unmount()
}, 3000)
```
works with `.babelrc`
```
{
  "plugins": [
    [
      "transform-react-jsx",
      { "pragma": "h" }
    ]
  ]
}
```
I would like to use import-syntax instead:
`import { h, render, Component, Text } from 'ink'`

If I edit `.babelrc` to:
```
{
  "presets": ["env"],
  "plugins": [
    [
      "transform-react-jsx",
      { "pragma": "h" }
    ]
  ]
}
```
I get:
```
.../ink/main.js:81
		var _this = _possibleConstructorReturn(this, (Counter.__proto__ || Object.getPrototypeOf(Counter)).call(this));
		                                                                                                   ^

TypeError: Class constructor Component cannot be invoked without 'new'
    at new Counter (/Users/petri/src/programming-survey-dsl/ink/main.js:68:16)
    at Instance.mount (/Users/petri/src/programming-survey-dsl/ink/node_modules/ink/lib/instance.js:86:21)
    at diff (/Users/petri/src/programming-survey-dsl/ink/node_modules/ink/lib/diff.js:40:16)
    at build (/Users/petri/src/programming-survey-dsl/ink/node_modules/ink/index.js:27:25)
    at update (/Users/petri/src/programming-survey-dsl/ink/node_modules/ink/index.js:64:20)
    at exports.render (/Users/petri/src/programming-survey-dsl/ink/node_modules/ink/index.js:80:2)
    at Object.<anonymous> (/Users/petri/src/programming-survey-dsl/ink/main.js:101:17)
    at Module._compile (module.js:624:30)
    at loader (/Users/petri/src/programming-survey-dsl/ink/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/petri/src/programming-survey-dsl/ink/node_modules/babel-register/lib/node.js:154:7)
```
I'm running on:
```
$ node -v
v8.5.0
```

**Comment by vadimdemedes** [comment]
This is a known problem for years - https://github.com/babel/babel/issues/4269. As a workaround, you can disable class transpilation.

**Comment by pe3** [comment]
Thanks. Will try it out.
