### ISSUE TITLE
useEffect cleanups not called. Regression 3.1.0-3.2.0

### ISSUE THREAD

**Issue by AriPerkkio** [vadimdemedes/ink#482]
When updating `ink@3.1.0` to `ink@3.2.0` my tests started to fail: https://github.com/AriPerkkio/eslint-remote-tester/pull/287.

It seems that `useEffect` cleanup functions are not called in `3.2.0`. Below is a minimal repro:

```jsx
import React, { useEffect } from "react";
import { Text } from "ink";
import { render } from "ink-testing-library";

test("ink repro", () => {
  const events = [];

  function MyComponent() {
    useEffect(() => {
      events.push("mounted");

      return function cleanup() {
        events.push("unmounted");
      };
    }, []);

    return <Text>Hello</Text>;
  }

  const { unmount } = render(<MyComponent />);

  unmount();

  expect(events).toStrictEqual(["mounted", "unmounted"]);
});
```

Had some trouble getting minimal jsx+babel+jest setup, but this works:
```json
{
  "scripts": {
    "test": "jest"
  },
  "dependencies": {
    "ink": "3.2.0",
    "react": "^17.0.2"
  },
  "devDependencies": {
    "@babel/core": "^7.15.8",
    "@babel/preset-env": "^7.15.8",
    "@babel/preset-react": "^7.14.5",
    "babel-jest": "^27.2.5",
    "babel-preset-jest": "^27.2.0",
    "ink-testing-library": "^2.1.0",
    "jest": "^27.2.5",
    "react-test-renderer": "^17.0.2"
  },
  "babel": {
    "presets": [
      "@babel/preset-env",
      "@babel/preset-react"
    ]
  },
  "jest": {
    "testEnvironment": "jsdom",
    "transform": {
      "\\.[jt]sx?$": "babel-jest"
    }
  }
}
```

`ink@3.1.0`:

```
 PASS  ./index.test.js
  ✓ ink repro (70 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.159 s
Ran all test suites.
Done in 1.80s.
```

`ink@3.2.0`:

```
 FAIL  ./index.test.js
  ✕ ink repro (5 ms)

  ● ink repro

    expect(received).toStrictEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 0

      Array [
        "mounted",
    -   "unmounted",
      ]

      21 |   unmount();
      22 |
    > 23 |   expect(events).toStrictEqual(["mounted", "unmounted"]);
         |                  ^
      24 | });
      25 |

      at Object.<anonymous> (index.test.js:23:18)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:387:19)
```

**Comment by vadimdemedes** [comment]
Hm, I'm wondering why it worked before in your case, since `useEffect` isn't executed immediately after render (but `useLayoutEffect` is). I added a similar test to `ink-testing-library` and confirmed it only passes with `useLayoutEffect` → https://github.com/vadimdemedes/ink-testing-library/commit/ed888b5bdcc746626db96c821c88248a8aadf1cb. I see you're using Jest, perhaps it patches `setTimeout` somehow that would explain this? Can you try the same script without Jest and see if it succeeds?

**Comment by AriPerkkio** [comment]
> [...] since `useEffect` isn't executed immediately

Oh that's right! My tests should actually wait for the cleanup call after the unmount.

Though it is weird why this is appearing now. Below is a script run without `jest`. It seems that with `ink@3.2.0` the cleanup function is properly called after all - just not synchronously. 

```js
// Run as `node index.mjs`

import React, { useEffect } from "react";
import { Text } from "ink";
import { render } from "ink-testing-library";

const events = [];

function MyComponent() {
  useEffect(() => {
    events.push("mounted");

    return function cleanup() {
      events.push("unmounted");
    };
  }, []);

  return React.createElement(Text, null, "Hello");
}

const { unmount } = render(React.createElement(MyComponent));
console.log("After render", events);

unmount();
console.log("After unmount", events);

new Promise((r) => setTimeout(r, 16)).then(() =>
  console.log("After 16ms react batch time", events)
);

// ink@3.1.0
// After render []
// After unmount [ 'mounted', 'unmounted' ]
// After 16ms react batch time [ 'mounted', 'unmounted' ]

// ink@3.2.0
// After render []
// After unmount [ 'mounted' ]
// After 16ms react batch time [ 'mounted', 'unmounted' ]
```
