### ISSUE TITLE
ink-text-input and ink-select-input do not seem to work at all with the latest ink + Node >= 16?

### ISSUE THREAD

**Issue by dcominottim** [vadimdemedes/ink#524]
For example, I get the following error when trying to run the very same example code from ink-select-input's readme:

```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `Demo`.
    at Demo
    at App (/Users/danilo.marques/Documents/invowk-js/node_modules/ink/build/components/App.js:42:9)
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `Demo`.
    at Demo
    at App (/Users/danilo.marques/Documents/invowk-js/node_modules/ink/build/components/App.js:42:9)

  ERROR  Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

        Check the render method of `Demo`.
```

I am correctly using ES6 Modules/imports everywhere. 

The built-in 'Text' component from ink, for instance, works fine. Any ideas?

**Comment by vadimdemedes** [comment]
Closing because this user has been blocked.
