### ISSUE TITLE
React 19 support

### ISSUE THREAD

**Issue by dumbmatter** [vadimdemedes/ink#688]
It seems that the current version of ink does not work with React 19. For example with some minimal code like this:

```js
import React from 'react';
import {render, Text} from 'ink';

render(React.createElement(Text, null, "Hello world"));
```

I get this output with react 18.3.1:

```
$ node index.js
Hello world
```

And this with react 19.0.0:

```
$ node index.js
/home/user/ink-react-19/node_modules/.pnpm/react-reconciler@0.29.2_react@19.0.0/node_modules/react-reconciler/cjs/react-reconciler.development.js:491
var ReactCurrentOwner = ReactSharedInternals.ReactCurrentOwner;
                                             ^

TypeError: Cannot read properties of undefined (reading 'ReactCurrentOwner')
    at $$$reconciler (/home/user/ink-react-19/node_modules/.pnpm/react-reconciler@0.29.2_react@19.0.0/node_modules/react-reconciler/cjs/react-reconciler.development.js:491:46)
    at file:///home/user/ink-react-19/node_modules/.pnpm/ink@5.1.0_react@19.0.0/node_modules/ink/build/reconciler.js:61:16

Node.js v22.11.0
```

**Comment by marviobezerra** [comment]
Same here

**Comment by MattyBalaam** [comment]
Is someone using React internals? Hope they don't get fired.

**Comment by KrisWis** [comment]
So the only thing left is to either downgrade React to version 18 or just wait?

**Comment by KrisWis** [comment]
But, the thing is, I don't use ink directly, I use Loki (for UI tests in conjunction with Storybook), and it in turn uses react-reconciler, which already uses ink. It's like this /:

**Comment by KrisWis** [comment]
> @KrisWis There's a temporary fork with a viable React 19 upgrade: https://github.com/QuentinFontenay/ink/tree/react-v19.0.0

But, the thing is, I don't use ink directly, I use Loki (for UI tests in conjunction with Storybook), and it in turn uses react-reconciler, which already uses ink. It's like this /:

**Comment by jakubmazanec** [comment]
Based on the forked and updated Ink linked above (thank you @QuentinFontenay), I created this patch: https://gist.github.com/jakubmazanec/3b2b0c86bb7f34fe9ae0937d608b590b

Use package `patch-package` to apply it, and also add following overrides to your `package.json`:

```
"overrides": {
  "react": "^19.0.0",
  "react-dom": "^19.0.0",
  "react-reconciler": "^0.31.0"
}
```

Overriding `react-reconciler` is needed, overriding React is maybe needed only in my specific case. Anyway, my Ink app seems to be working now.

@sindresorhus I know you're probably very busy, but as a new maintainer (AFAIK), could you please give us some timeline when Ink will be fixed? Thank you.

**Comment by sindresorhus** [comment]
A pull request with the minimum amount of changes to add React 19 support is welcome.

**Comment by nicoladefranceschi** [comment]
👍

**Comment by TomFreudenberg** [comment]
+1 :-)

**Comment by tianhuil** [comment]
As a hot fix, can we push a patch that prints a better error message in this corner case and link to this thread?  For me, downgrading to react 18 wasn't a big deal but discovering this was a fix took a while.

**Comment by Lotes** [comment]
For those who depend on React 19 and Ink in the same package: NPM can install multiple versions of the same package into your `package.json`. This might be not new to everybody (I found out very late). Here a snippet from a `package.json` using 2 versions of Langium:

```json
"dependencies": {
    "langium2": "npm:langium@^2.0.0",
    "langium3": "npm:langium@^3.0.0"
}
```

Here is how to call them:

```ts
import { EmptyFileSystem as E2, createLangiumGrammarServices as G2 } from 'langium2';
import { EmptyFileSystem as E3 } from 'langium3';
import { createLangiumGrammarServices as G3 } from 'langium3/grammar';

console.log(G2(E2).grammar.Grammar.name);
console.log(G3(E3).grammar.Grammar.name);
```

I will try out a scenario for Ink later this day using two React versions. I might update my post then...

**Comment by bondarenkod** [comment]
It is something wrong with the pr? Except the merge conflict. 
https://github.com/vadimdemedes/ink/pull/656

**Comment by anerli** [comment]
Our CLI is installed as a dev dep in projects that may contain react already - so we have to use react as peer dep to avoid duplicate React instances interfering with one another. The patch listed above and fork alternatives are difficult to get working - haven't had any luck. Since we need a single peer dep and can't enforce that the users of our lib use React 18, downgrading isn't an option. Would save us a lot of problems for React 19 to be supported on ink, don't think I'm familiar enough to implement but would really appreciate this fix

**Comment by Russiee** [comment]
Any progress on this? It's the final blocker on migration to React 19 for ourselves and given the PR above seems to be a fairly minor fix.

**Comment by maelp** [comment]
I have the same issue, it seems linked to `react-reconciler`, any idea how to solve?

**Comment by dumbmatter** [comment]
OpenAI Codex [uses Ink and React 18 in their CLI](https://github.com/openai/codex/blob/5746561428cef1869fca906a06c2091435dffb9d/codex-cli/package.json#L40-L48). If the hype is real, maybe it can fix this issue!

**Comment by bradleyayers** [comment]
> `react-reconciler`

ink depends on an old version of react-reconciler (0.29.x rather than 0.32.x), and yarn gives a warning about it:

➤ YN0060: │ react is listed by your project with version 19.1.0 (pd4d24), which doesn't satisfy what react-reconciler (via ink) and other dependencies request (but they have non-overlapping ranges!).
