### ISSUE TITLE
Separate component files not working

### ISSUE THREAD

**Issue by jrschumacher** [vadimdemedes/ink#92]
When I extract my components into their own files I get the following error:

```
> TestComp.js:8
		return (<div>Hello</div>);
		        ^

SyntaxError: Unexpected token <
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:670:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

Example:

```
// TestComp.js
'use strict';

const {h, Component, Fragment, Color} = require('ink');
const PropTypes = require('prop-types');

class TestComp extends Component {
	render () {
		return (<div>Hello</div>);
	}
}

module.exports = TestComp;
```

```
// ui.js
'use strict';

const {h, Component, Fragment, Color} = require('ink');
const PropTypes = require('prop-types');
const TestComp = require('./TestComp');

// This works:
// class TestComp extends Component {
// 	render () {
// 		return (<div>Hello</div>);
// 	}
// }

class UI extends Component {
	render() {
		return (
			<TestComp />
		);
	}
}

module.exports = UI;
```

**Comment by rjoydip** [comment]
I am getting the same issue `SyntaxError: Unexpected token <`

**Comment by jrschumacher** [comment]
@rjoydip I had to use the `import-jsx` module to get it working.

**Comment by vadimdemedes** [comment]
@jrschumacher is right, either you need to transpile JSX using Babel or any other tool or use [import-jsx](https://github.com/vadimdemedes/import-jsx).
